name: Checkout, install and run webpack
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches: 
      - 'master'

jobs:
  build:
    name: Run install and run production webpack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source into the VM
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Upgrade npm to v7
        run: npm install -g npm@latest
      - name: Install 
        run: npm ci --no-audit --no-optional
      - name: Create Webpack
        run: npm run webpack:production
