name: Create binaries for the current release
on:
  release:
    types: [created]
    
jobs:
  build:
    name: Create binaries for all supported OSs
    runs-on: macos-latest
    steps:
      - name: Checkout the source into the VM
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Upgrade npm to v7
        run: npm install -g npm@latest
      - name: Install 
        run: npm ci --no-audit
      - name: Create Webpack
        run: npm run webpack:production
      - name: Import OS-X certificates
        run: chmod +x ./.github/workflows/add-osx-cert.sh && ./.github/workflows/add-osx-cert.sh
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      - name: publish multi-platform binaries
        run: npm run release
        env:
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
          WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EP_PRE_RELEASE: ${{ secrets.EP_PRE_RELEASE }}
          EP_GH_IGNORE_TIME: ${{ secrets.EP_GH_IGNORE_TIME }}
      